Fix LilyPond crashing on power chords
It would fail with
```
ERROR: In procedure caddr:
In procedure caddr: Wrong type (expecting pair): ()
```
Since `caddr` is supposed to grab the third element of a list, this is
not very surprising. We write a helper `grab-fifth`, that grabs the
third element of the chord, or falls back on second or first element.